GET http://localhost:3000/api/users/login


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "nickName":"Test"
}


###
POST http://localhost:3000/api/palettes?userid=62c80148c3ec8e57fd52976e
Content-Type: application/json

